# TODO: config file with list of all set events, /event add, /event changes that
# There will be specified "event-sources" setting in config file with possible options "slime" or "config" (Or just asp-hook-enabled: true/false)
# "slime" option will hook to ASP and try to get the list of slime worlds
# "config" option will take values from "events" setting

# If the list of available events should be taken from the Advanced Slime World Manager plugin hook
aswm-hook-enabled: false

# List of events if the `aswm-hook-enabled` option is set to false
event-list: []
