# TODO: config file with list of all set events, /event add, /event changes that
# There will be specified "event-sources" setting in config file with possible options "slime" or "config" (Or just asp-hook-enabled: true/false)
# "slime" option will hook to ASP and try to get the list of slime worlds
# "config" option will take values from "events" setting

language: en.yml

# TODO: Add default configuration for newly created event worlds
default-cfg:
    spawnX: 0
    spawnY: 100
    spawnZ: 0
    spawnYaw: 0.0
    difficulty: PEACEFUL
    allowMonsters: false
    allowAnimals: false
    dragonBattle: false
    pvp: false
    environment: NORMAL
    worldtype: DEFAULT
    defaultBiome: minecraft:plains
    loadOnStartup: false
    saveBlockTicks: true
    saveFluidTicks: true
    savePOI: true
