main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21"
author: Davisiiiik

description: Simple plugin for event and minigame management

depend:
  - ASPaperPlugin
softdepend:
  - CMI

commands:
  event:
    description: Base command for TerminusCraft Plugin Manager
    usage: "For a list of commands, type /event help"
    aliases: [em]

permissions:
  event.*:
    description: Grants all Event Manager plugin permissions
    default: false
    children:
      event.player.*: true
      event.admin.*: true

  ### Default player permissions ###
  event.player.*:
    description: Grants all permissions for player usage
    default: true
    children:
      event.player.help: true
      event.player.current: true
      event.player.join: true
      event.player.leave: true
      event.player.list: true

  event.player.help:
    description: Show a list of available Event Manager commands.
    default: false

  event.player.current:
    description: Show information about the currently running Event.
    default: false

  event.player.join:
    description: Join the currently running Event.
    default: false

  event.player.leave:
    description: Leave the currently running Event.
    default: false

  event.player.list:
    description: Show a list of all existing Events.
    default: false

  ### Administrator permissions ###
  event.admin.*:
    description: Grants all permissions for admin Event management
    default: op
    children:
      event.admin.tp: true
      event.admin.start: true
      event.admin.stop: true
      event.admin.add: true
      event.admin.create: true
      event.admin.setspawn: true
      event.admin.remove: true
      event.admin.delete: true
      event.admin.unload: true
      event.admin.saveconfigs: true
      event.admin.reload: true
      event.admin.bypass: true
      event.admin.verbose: true
      event.admin.build.*: true

  event.admin.tp:
    description: Teleport to any Event location.
    default: false

  event.admin.start:
    description: Start an Event.
    default: false

  event.admin.stop:
    description: Stop the currently running Event.
    default: false

  event.admin.add:
    description: Add an Event with already existing World to the Event Manager system.
    default: false

  event.admin.create:
    description: Create a new Event with a blank world.
    default: false

  event.admin.setspawn:
    description: Set the spawn point for an Event.
    default: false

  event.admin.remove:
    description: Remove an Event from the system, but preserve its world.
    default: false

  event.admin.delete:
    description: Delete an Event and its world permanently.
    default: false

  event.admin.unload:
    description: Unload an Event world from active memory.
    default: false

  event.admin.saveconfigs:
    description: Save all Event world configurations to events.yml file.
    default: false

  event.admin.reload:
    description: Reload Event Manager configurations.
    default: false

  event.admin.bypass:
    description: Bypass the automatic teleportation on server join.
    default: false

  event.admin.verbose:
    description: Show additional information on event list command.
    default: false

  ### Administrator world-protection related permissions ###
  event.admin.build.*:
    description: Grants break, place and interact permissions
    default: false
    children:
      event.admin.break.*: true
      event.admin.place.*: true
      event.admin.interact.*: true

  event.admin.break.*:
    description: Can break blocks in every event world.
    default: false

  event.admin.place.*:
    description: Can place blocks in every event world.
    default: false

  event.admin.interact.*:
    description: Can interact with blocks in every event world.
    default: false
