main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21"
author: Davisiiiik

description: Simple plugin for event and minigame management

depend:
  - ASPaperPlugin
softdepend:
  - CMI

commands:
  event:
    description: Base command for TerminusCraft Plugin Manager
    usage: "For a list of commands, type /event help"
    aliases: [em]

permissions:
  eventmng.*:
    description: Grants all Event Manager plugin permissions
    default: false
    children:
      eventmng.player.*: true
      eventmng.admin.*: true

  eventmng.player.*:
    description: Grants all permissions for player usage
    default: true
    children:
      eventmng.player.help: true
      eventmng.player.current: true
      eventmng.player.join: true
      eventmng.player.leave: true
      eventmng.player.list: true

  eventmng.admin.*:
    description: Grants all permissions for admin Event management
    default: op
    children:
      eventmng.admin.tp: true
      eventmng.admin.start: true
      eventmng.admin.stop: true
      eventmng.admin.add: true
      eventmng.admin.create: true
      eventmng.admin.setspawn: true
      eventmng.admin.remove: true
      eventmng.admin.delete: true
      eventmng.admin.unload: true
      eventmng.admin.savecfgs: true
      eventmng.admin.reload: true

  eventmng.player.help:
    description: Show a list of available Event Manager commands.
    default: false

  eventmng.player.current:
    description: Show information about the currently running Event.
    default: false

  eventmng.player.join:
    description: Join the currently running Event.
    default: false

  eventmng.player.leave:
    description: Leave the currently running Event.
    default: false

  eventmng.player.list:
    description: Show a list of all existing Events.
    default: false

  eventmng.admin.tp:
    description: Teleport to any Event location.
    default: false

  eventmng.admin.start:
    description: Start an Event.
    default: false

  eventmng.admin.stop:
    description: Stop the currently running Event.
    default: false

  eventmng.admin.add:
    description: Add an Event with already existing World to the Event Manager system.
    default: false

  eventmng.admin.create:
    description: Create a new Event with a blank world.
    default: false

  eventmng.admin.setspawn:
    description: Set the spawn point for an Event.
    default: false

  eventmng.admin.remove:
    description: Remove an Event from the system, but preserve its world.
    default: false

  eventmng.admin.delete:
    description: Delete an Event and its world permanently.
    default: false

  eventmng.admin.unload:
    description: Unload an Event world from active memory.
    default: false

  eventmng.admin.savecfgs:
    description: Save all Event world configurations to events.yml file.
    default: false

  eventmng.admin.reload:
    description: Reload Event Manager configurations.
    default: false
