name: Feature request
description: Suggest an idea for this Minecraft plugin
labels: "\U0001F4A1 Feature Request"
assignees: Davisiiiik

body:
  - type: markdown
    attributes:
      value: |
        ## Plugin Manager Issues Tracker

  - id: description
    type: textarea
    validations:
      required: true
    attributes:
      label: 'Describe the Feature request'
      description: |
        A clear and concise description of what you want to be implemented to the plugin.
      placeholder: |
        [Insert what exactly you want to add]

  - id: extra
    type: textarea
    attributes:
      label: 'Additional Information'
      description: |
        Additional information that can help understanding the issue.
        Config files, clips, screenshots, etc are more than welcome.
      placeholder: |
        [Drag and drop an image or video onto this field to upload it. Otherwise please use pastebin for configs]

  - type: markdown
    attributes:
      value: |
        ## Thank you for helping improve Plugin Manager!
        Please remember to check back for any questions being asked and reply back as soon as you can!
